module.exports = [
  {
    name: 'News & current events',
    slug: 'news-current-events',
    order: 1,
    subCategories: [
      { name: 'Breaking news', slug: 'breaking-news' },
      { name: 'World news', slug: 'world-news' },
      { name: 'Local & regional news', slug: 'local-regional-news' },
      { name: 'Economy & markets news', slug: 'economy-markets-news' },
      { name: 'Crime & justice news', slug: 'crime-justice-news' },
      { name: 'Weather & natural disasters', slug: 'weather-natural-disasters' },
      { name: 'Elections & political news (current cycle)', slug: 'elections-political-news-current-cycle' },
      { name: 'Conflicts & geopolitics', slug: 'conflicts-geopolitics' },
      { name: 'Business news', slug: 'business-news' },
      { name: 'Media & journalism industry', slug: 'media-journalism-industry' },
    ],
  },
  {
    name: 'Politics & society',
    slug: 'politics-society',
    order: 2,
    subCategories: [
      { name: 'Domestic politics', slug: 'domestic-politics' },
      { name: 'International politics', slug: 'international-politics' },
      { name: 'Public policy & government', slug: 'public-policy-government' },
      { name: 'Human rights & civil liberties', slug: 'human-rights-civil-liberties' },
      { name: 'Social justice & activism', slug: 'social-justice-activism' },
      { name: 'Immigration & borders', slug: 'immigration-borders' },
      { name: 'Law & legal systems', slug: 'law-legal-systems' },
      { name: 'Political parties & ideologies', slug: 'political-parties-ideologies' },
      { name: 'Public opinion & polling', slug: 'public-opinion-polling' },
      { name: 'Civic engagement & voting', slug: 'civic-engagement-voting' },
    ],
  },
  {
    name: 'Sports',
    slug: 'sports',
    order: 3,
    subCategories: [
      { name: 'Football / Soccer', slug: 'football-soccer' },
      { name: 'Cricket', slug: 'cricket' },
      { name: 'Basketball', slug: 'basketball' },
      { name: 'American football', slug: 'american-football' },
      { name: 'Tennis', slug: 'tennis' },
      { name: 'Combat sports (Boxing, MMA, WWE)', slug: 'combat-sports' },
      { name: 'Motorsports (F1, MotoGP, NASCAR)', slug: 'motorsports' },
      { name: 'Baseball', slug: 'baseball' },
      { name: 'Olympic sports', slug: 'olympic-sports' },
      { name: 'Esports', slug: 'esports' },
      { name: 'Specific leagues', slug: 'specific-leagues' },
      { name: 'Specific teams & clubs', slug: 'specific-teams-clubs' },
    ],
  },
  {
    name: 'Entertainment',
    slug: 'entertainment',
    order: 4,
    subCategories: [
      { name: 'Movies', slug: 'movies' },
      { name: 'TV shows & series', slug: 'tv-shows-series' },
      { name: 'Streaming platforms & originals', slug: 'streaming-platforms-originals' },
      { name: 'Celebrities & pop culture', slug: 'celebrities-pop-culture' },
      { name: 'Reality TV', slug: 'reality-tv' },
      { name: 'Comedy & stand-up', slug: 'comedy-standup' },
      { name: 'Anime & manga', slug: 'anime-manga' },
      { name: 'Comics & graphic novels', slug: 'comics-graphic-novels' },
      { name: 'Award shows & red carpets', slug: 'award-shows-red-carpets' },
      { name: 'Entertainment gossip & fan culture', slug: 'entertainment-gossip-fan-culture' },
    ],
  },
  {
    name: 'Music',
    slug: 'music',
    order: 5,
    subCategories: [
      { name: 'Pop music', slug: 'pop-music' },
      { name: 'Hip-hop & rap', slug: 'hip-hop-rap' },
      { name: 'Rock & metal', slug: 'rock-metal' },
      { name: 'EDM & dance', slug: 'edm-dance' },
      { name: 'R&B & soul', slug: 'rnb-soul' },
      { name: 'Classical & instrumental', slug: 'classical-instrumental' },
      { name: 'Indie & alternative', slug: 'indie-alternative' },
      { name: 'K-pop / J-pop', slug: 'kpop-jpop' },
      { name: 'Regional & folk music', slug: 'regional-folk-music' },
      { name: 'Music festivals & concerts', slug: 'music-festivals-concerts' },
      { name: 'Music production & DJing', slug: 'music-production-djing' },
      { name: 'Artists & bands (by name)', slug: 'artists-bands' },
    ],
  },
  {
    name: 'Gaming',
    slug: 'gaming',
    order: 6,
    subCategories: [
      { name: 'PC gaming', slug: 'pc-gaming' },
      { name: 'Console gaming', slug: 'console-gaming' },
      { name: 'Mobile gaming', slug: 'mobile-gaming' },
      { name: 'Battle royale games', slug: 'battle-royale-games' },
      { name: 'Competitive shooters', slug: 'competitive-shooters' },
      { name: 'RPGs & open world games', slug: 'rpgs-open-world-games' },
      { name: 'Sports & racing games', slug: 'sports-racing-games' },
      { name: 'Strategy & simulation games', slug: 'strategy-simulation-games' },
      { name: 'Esports teams & tournaments', slug: 'esports-teams-tournaments' },
      { name: 'Game development & design', slug: 'game-development-design' },
      { name: 'Retro & classic games', slug: 'retro-classic-games' },
    ],
  },
  {
    name: 'Business & finance',
    slug: 'business-finance',
    order: 7,
    subCategories: [
      { name: 'Stock market & investing', slug: 'stock-market-investing' },
      { name: 'Crypto & blockchain', slug: 'crypto-blockchain' },
      { name: 'Personal finance & budgeting', slug: 'personal-finance-budgeting' },
      { name: 'Startups & entrepreneurship', slug: 'startups-entrepreneurship' },
      { name: 'Venture capital & angel investing', slug: 'venture-capital-angel-investing' },
      { name: 'Real estate & property', slug: 'real-estate-property' },
      { name: 'Business strategy & management', slug: 'business-strategy-management' },
      { name: 'E-commerce & online business', slug: 'ecommerce-online-business' },
      { name: 'Macroeconomics & policy impact', slug: 'macroeconomics-policy-impact' },
      { name: 'Fintech & digital payments', slug: 'fintech-digital-payments' },
      { name: 'Small business & freelancers', slug: 'small-business-freelancers' },
    ],
  },
  {
    name: 'Technology',
    slug: 'technology',
    order: 8,
    subCategories: [
      { name: 'AI & machine learning', slug: 'ai-machine-learning' },
      { name: 'Software development & programming', slug: 'software-development-programming' },
      { name: 'Web & mobile apps', slug: 'web-mobile-apps' },
      { name: 'Gadgets & consumer electronics', slug: 'gadgets-consumer-electronics' },
      { name: 'Smartphones & devices', slug: 'smartphones-devices' },
      { name: 'Cloud computing & DevOps', slug: 'cloud-computing-devops' },
      { name: 'Cybersecurity & privacy', slug: 'cybersecurity-privacy' },
      { name: 'Data science & analytics', slug: 'data-science-analytics' },
      { name: 'Robotics & automation', slug: 'robotics-automation' },
      { name: 'Big tech companies', slug: 'big-tech-companies' },
      { name: 'Tech startups & innovation', slug: 'tech-startups-innovation' },
    ],
  },
  {
    name: 'Science',
    slug: 'science',
    order: 9,
    subCategories: [
      { name: 'Space & astronomy', slug: 'space-astronomy' },
      { name: 'Physics', slug: 'physics' },
      { name: 'Biology & life sciences', slug: 'biology-life-sciences' },
      { name: 'Chemistry & materials', slug: 'chemistry-materials' },
      { name: 'Earth science & climate', slug: 'earth-science-climate' },
      { name: 'Environmental science', slug: 'environmental-science' },
      { name: 'Medicine & biomedical research', slug: 'medicine-biomedical-research' },
      { name: 'Psychology & neuroscience', slug: 'psychology-neuroscience' },
      { name: 'Science news & discoveries', slug: 'science-news-discoveries' },
      { name: 'Science communication & education', slug: 'science-communication-education' },
    ],
  },
  {
    name: 'Education & learning',
    slug: 'education-learning',
    order: 10,
    subCategories: [
      { name: 'School & university life', slug: 'school-university-life' },
      { name: 'Online courses & MOOCs', slug: 'online-courses-moocs' },
      { name: 'Study tips & productivity for students', slug: 'study-tips-productivity-students' },
      { name: 'Exams & test prep', slug: 'exams-test-prep' },
      { name: 'Language learning', slug: 'language-learning' },
      { name: 'Professional certifications', slug: 'professional-certifications' },
      { name: 'Adult & lifelong learning', slug: 'adult-lifelong-learning' },
      { name: 'Teaching & pedagogy', slug: 'teaching-pedagogy' },
      { name: 'Homeschooling & alternative education', slug: 'homeschooling-alternative-education' },
      { name: 'Academic research & publications', slug: 'academic-research-publications' },
    ],
  },
  {
    name: 'Careers',
    slug: 'careers',
    order: 11,
    subCategories: [
      { name: 'Job search & interviewing', slug: 'job-search-interviewing' },
      { name: 'Resume & portfolio tips', slug: 'resume-portfolio-tips' },
      { name: 'Workplace culture & dynamics', slug: 'workplace-culture-dynamics' },
      { name: 'Career change & transitions', slug: 'career-change-transitions' },
      { name: 'Remote work & digital nomads', slug: 'remote-work-digital-nomads' },
      { name: 'Leadership & management careers', slug: 'leadership-management-careers' },
      { name: 'Freelancing & gig work', slug: 'freelancing-gig-work' },
      { name: 'Corporate careers & industry paths', slug: 'corporate-careers-industry-paths' },
      { name: 'Internships & early career', slug: 'internships-early-career' },
      { name: 'Negotiation & salary talk', slug: 'negotiation-salary-talk' },
    ],
  },
  {
    name: 'Arts & culture',
    slug: 'arts-culture',
    order: 12,
    subCategories: [
      { name: 'Visual arts', slug: 'visual-arts' },
      { name: 'Photography', slug: 'photography' },
      { name: 'Design & illustration', slug: 'design-illustration' },
      { name: 'Architecture & urban design', slug: 'architecture-urban-design' },
      { name: 'Literature & fiction', slug: 'literature-fiction' },
      { name: 'Poetry & creative writing', slug: 'poetry-creative-writing' },
      { name: 'Theatre & performing arts', slug: 'theatre-performing-arts' },
      { name: 'Dance', slug: 'dance' },
      { name: 'Museums & galleries', slug: 'museums-galleries' },
      { name: 'Cultural heritage & traditions', slug: 'cultural-heritage-traditions' },
      { name: 'Street art & pop culture art', slug: 'street-art-pop-culture-art' },
    ],
  },
  {
    name: 'Travel',
    slug: 'travel',
    order: 13,
    subCategories: [
      { name: 'Travel inspiration & destinations', slug: 'travel-inspiration-destinations' },
      { name: 'Budget travel & backpacking', slug: 'budget-travel-backpacking' },
      { name: 'Luxury travel', slug: 'luxury-travel' },
      { name: 'Solo travel', slug: 'solo-travel' },
      { name: 'Road trips', slug: 'road-trips' },
      { name: 'Adventure & outdoor travel', slug: 'adventure-outdoor-travel' },
      { name: 'City guides & local tips', slug: 'city-guides-local-tips' },
      { name: 'Cultural tourism & heritage sites', slug: 'cultural-tourism-heritage-sites' },
      { name: 'Travel planning & hacks', slug: 'travel-planning-hacks' },
      { name: 'Hotels, hostels & stays', slug: 'hotels-hostels-stays' },
      { name: 'Flights & airlines', slug: 'flights-airlines' },
    ],
  },
  {
    name: 'Food & drink',
    slug: 'food-drink',
    order: 14,
    subCategories: [
      { name: 'Recipes & home cooking', slug: 'recipes-home-cooking' },
      { name: 'Street food', slug: 'street-food' },
      { name: 'Restaurants & dining out', slug: 'restaurants-dining-out' },
      { name: 'Baking & desserts', slug: 'baking-desserts' },
      { name: 'Vegetarian & vegan food', slug: 'vegetarian-vegan-food' },
      { name: 'Regional cuisines', slug: 'regional-cuisines' },
      { name: 'Coffee culture', slug: 'coffee-culture' },
      { name: 'Tea culture', slug: 'tea-culture' },
      { name: 'Non-alcoholic drinks & mocktails', slug: 'non-alcoholic-drinks-mocktails' },
      { name: 'Food photography & styling', slug: 'food-photography-styling' },
      { name: 'Nutrition & healthy eating', slug: 'nutrition-healthy-eating' },
    ],
  },
  {
    name: 'Fashion & beauty',
    slug: 'fashion-beauty',
    order: 15,
    subCategories: [
      { name: 'Fashion trends & runway', slug: 'fashion-trends-runway' },
      { name: 'Streetwear & casual style', slug: 'streetwear-casual-style' },
      { name: 'Traditional & cultural fashion', slug: 'traditional-cultural-fashion' },
      { name: 'Personal style & outfit ideas', slug: 'personal-style-outfit-ideas' },
      { name: 'Skincare', slug: 'skincare' },
      { name: 'Makeup & cosmetics', slug: 'makeup-cosmetics' },
      { name: 'Haircare & hairstyles', slug: 'haircare-hairstyles' },
      { name: 'Nails & grooming', slug: 'nails-grooming' },
      { name: 'Fashion influencers & brands', slug: 'fashion-influencers-brands' },
      { name: 'Sustainable & ethical fashion', slug: 'sustainable-ethical-fashion' },
    ],
  },
  {
    name: 'Lifestyle',
    slug: 'lifestyle',
    order: 16,
    subCategories: [
      { name: 'Minimalism & decluttering', slug: 'minimalism-decluttering' },
      { name: 'Home decor & interiors', slug: 'home-decor-interiors' },
      { name: 'Productivity & time management', slug: 'productivity-time-management' },
      { name: 'Personal development & self-help', slug: 'personal-development-self-help' },
      { name: 'Mindfulness & habits', slug: 'mindfulness-habits' },
      { name: 'Hobbies & leisure', slug: 'hobbies-leisure' },
      { name: 'Organization & planning', slug: 'organization-planning' },
      { name: 'Digital life & social media habits', slug: 'digital-life-social-media-habits' },
      { name: 'Urban vs. rural lifestyles', slug: 'urban-vs-rural-lifestyles' },
      { name: 'Life hacks & everyday tips', slug: 'life-hacks-everyday-tips' },
    ],
  },
  {
    name: 'Health',
    slug: 'health',
    order: 17,
    subCategories: [
      { name: 'Fitness & exercise', slug: 'fitness-exercise' },
      { name: 'Nutrition & diet plans', slug: 'nutrition-diet-plans' },
      { name: 'Mental health & wellbeing', slug: 'mental-health-wellbeing' },
      { name: 'Sleep & recovery', slug: 'sleep-recovery' },
      { name: 'Weight management', slug: 'weight-management' },
      { name: 'Yoga & meditation', slug: 'yoga-meditation' },
      { name: 'Chronic conditions & health journeys', slug: 'chronic-conditions-health-journeys' },
      { name: 'Public health & epidemiology', slug: 'public-health-epidemiology' },
      { name: 'Sexual health & education', slug: 'sexual-health-education' },
      { name: 'Health tech & wearables', slug: 'health-tech-wearables' },
    ],
  },
  {
    name: 'Nature, animals & outdoors',
    slug: 'nature-animals-outdoors',
    order: 18,
    subCategories: [
      { name: 'Pets', slug: 'pets' },
      { name: 'Exotic pets & small animals', slug: 'exotic-pets-small-animals' },
      { name: 'Wildlife & conservation', slug: 'wildlife-conservation' },
      { name: 'Birdwatching & nature observation', slug: 'birdwatching-nature-observation' },
      { name: 'National parks & reserves', slug: 'national-parks-reserves' },
      { name: 'Hiking & trekking', slug: 'hiking-trekking' },
      { name: 'Camping & backpacking', slug: 'camping-backpacking' },
      { name: 'Fishing & hunting', slug: 'fishing-hunting' },
      { name: 'Nature photography', slug: 'nature-photography' },
      { name: 'Environmental issues & sustainability', slug: 'environmental-issues-sustainability' },
    ],
  },
  {
    name: 'Religion & spirituality',
    slug: 'religion-spirituality',
    order: 19,
    subCategories: [
      { name: 'Major world religions', slug: 'major-world-religions' },
      { name: 'Local & regional faith traditions', slug: 'local-regional-faith-traditions' },
      { name: 'Scriptures & religious texts', slug: 'scriptures-religious-texts' },
      { name: 'Rituals, festivals & observances', slug: 'rituals-festivals-observances' },
      { name: 'Spiritual practices', slug: 'spiritual-practices' },
      { name: 'Philosophy & meaning-of-life discussions', slug: 'philosophy-meaning-of-life' },
      { name: 'Interfaith dialogue', slug: 'interfaith-dialogue' },
      { name: 'Religious history & culture', slug: 'religious-history-culture' },
      { name: 'Spirituality & self-discovery', slug: 'spirituality-self-discovery' },
      { name: 'Religious communities & leaders', slug: 'religious-communities-leaders' },
    ],
  },
  {
    name: 'Family & relationships',
    slug: 'family-relationships',
    order: 20,
    subCategories: [
      { name: 'Dating & romance', slug: 'dating-romance' },
      { name: 'Marriage & long-term partnerships', slug: 'marriage-long-term-partnerships' },
      { name: 'Breakups & heartbreak', slug: 'breakups-heartbreak' },
      { name: 'Parenting & pregnancy', slug: 'parenting-pregnancy' },
      { name: 'Childcare & early childhood', slug: 'childcare-early-childhood' },
      { name: 'Teen & young adult parenting', slug: 'teen-young-adult-parenting' },
      { name: 'Friendships & social life', slug: 'friendships-social-life' },
      { name: 'Family dynamics & extended family', slug: 'family-dynamics-extended-family' },
      { name: 'Relationship advice & communication', slug: 'relationship-advice-communication' },
      { name: 'Caring for elders & multigenerational living', slug: 'caring-for-elders-multigenerational-living' },
    ],
  },
];
